<a href="https://colab.research.google.com/github/blackxhrt2102/Data-Science-tutorial/blob/main/Numpy_tutorial(Day_1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Modular Programming

**Modula programming refer to process of breaking a large programming task into separate smaller manageable subtask or modules.These individual modules can be cobbled together like building block to create a larger application.**

**Application of modular programming:-**
* 1.Simplicity.
* 2.Maintainability ( Since code is broken into smaller pieces their maintainability is easy:-)
* 3.Reusability

**Module-**
**A module can be accessed with import statement.**

**Collection of many modules can be referr as a library.**

# Numpy:-

A numpy stands for numerical python.It is a library consist of multidimensional array objects and a collection of routines of preprocessing of array.It simplily used to manipulate and process vectors and matrices.

In [2]:
# Importing numpy module:-

import numpy as np  

**The most important object defined in numpy is an N dimensional multidimension array type called as ndarray.**
* It stores data of same type.
* Each element takes same size of memory.

In [6]:
# Create 1 dimensional array:-
df=np.array([1,2,3,4,5])
print(df)

[1 2 3 4 5]


In [9]:
# Create 2 dimensional array:-
df=np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype='float')
print(df)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [12]:
# Create a 3 dimensional array:-
df=np.array([[[1,2,3,4],[3,4,5,6]],[[2,3,4,5],[4,5,0,4]]],dtype='float')
print(df)   # By counting the number of square brackets we can know the dimension;

[[[1. 2. 3. 4.]
  [3. 4. 5. 6.]]

 [[2. 3. 4. 5.]
  [4. 5. 0. 4.]]]


In [19]:
# Array Inspection:-

print('Shape of 3d array:->',df.shape)  # It describe the shape of 3D ndarray.

print('Dimension of array->',df.ndim)  # It describe the dimension of 3D array:-

print('Total number of elements in array->',df.size)  # It describe the total number of elements:-

Shape of 3d array:- (2, 2, 4)
Dimension of array- 3
Total number of elements in array- 16


In [23]:
# Initialization with zero:

df=np.zeros((2,3))    # (2,3)- 2nd row with 3 columns:-
print(df)             

[[0. 0. 0.]
 [0. 0. 0.]]


In [24]:
# Initialization with ones:-

df=np.ones((4,3),dtype='float')  
print(df)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
# Generate a range of numbers:-
df=np.arange(1,10)  # It starts with one enad at 9:
print(df)

df=np.arange(3,20,4)  # It starts with 3 and end at 19 with 4 number gap to skip.
print(df)

[1 2 3 4 5 6 7 8 9]
[ 3  7 11 15 19]


In [32]:
# Generate evenly spaced between two number

df=np.linspace(10,20,3)  # It start with 10 and end with 19 and equally distributed between 3 number.
print(df)

df1=np.linspace(1,28,23)  # Start with 1 and end with 28  and equally distributed between 23 number.
print(df1)

[10. 15. 20.]
[ 1.          2.22727273  3.45454545  4.68181818  5.90909091  7.13636364
  8.36363636  9.59090909 10.81818182 12.04545455 13.27272727 14.5
 15.72727273 16.95454545 18.18181818 19.40909091 20.63636364 21.86363636
 23.09090909 24.31818182 25.54545455 26.77272727 28.        ]


In [35]:
# To generate random integer 
df=np.random.random((3,4))  # Shape of 3 row and 4 columns
print(df)

[[0.80273541 0.599382   0.81739529 0.09351453]
 [0.61805962 0.72650371 0.947734   0.21895721]
 [0.06298466 0.75261964 0.02308034 0.39462482]]


In [38]:
# To generate random integer between two different integer
df=np.random.randint(19,109,size=(3,3))  # Generate number between 19 and 109 of size (3,3).
print(df)

[[54 28 31]
 [79 47 71]
 [60 82 49]]


In [54]:
# Change list to ndarray or change tuple to ndarray.
a=[1,2,3,4,5]
print('List',a,type(a))

a=np.asarray(a)
print('Numpy array->',a,type(a))


print('\n\n----------------------------------------------------------------------------------------------------------------------\n\n')

b=(1,2,3,4,5)
print('tuple',a,type(b))

b=np.asarray(b)
print('Numpy',b,type(b))



List [1, 2, 3, 4, 5] <class 'list'>
Numpy array-> [1 2 3 4 5] <class 'numpy.ndarray'>


----------------------------------------------------------------------------------------------------------------------


tuple [1 2 3 4 5] <class 'tuple'>
Numpy [1 2 3 4 5] <class 'numpy.ndarray'>


In [61]:
# Transpose
ab=np.array([[1,2,3,3],[2,3,4,5]])
print('Array-',ab)

print('Transpose of ab:-\n',np.transpose(ab))

Array- [[1 2 3 3]
 [2 3 4 5]]
Transpose of ab:-
 [[1 2]
 [2 3]
 [3 4]
 [3 5]]


In [66]:
# Reshape
ab=np.array([[1,2,3,3],[2,3,4,5]])
print(ab)
# Changing shape of ab to (4,2) --
print(np.reshape(ab,(4,2)))

[[1 2 3 3]
 [2 3 4 5]]
[[1 2]
 [3 3]
 [2 3]
 [4 5]]


In [77]:
# Argmax ->Return max element of array:-
a=np.array([[1,3,4],[5,3,2]])
np.argmax(a,axis=1)  # If axis=1 then from each row it tell the position of maximum element.

array([2, 0])

In [79]:
# Amax
np.amax(a,axis=1)  # It specifies the maximum element from each row.

array([4, 5])

In [82]:
a=np.array([2.4,4.5766,4.5])
print(a)

#------------------- Flooring -------------
print(np.floor(a))  # It floors the value.

[2.4    4.5766 4.5   ]
[2. 4. 4.]


In [83]:
# To iterate from multiple dimensional array
a=np.array([[1,2,3,4],[4,3,21,1]])
for i in np.nditer(a):
  print(i)

1
2
3
4
4
3
21
1


**Broadcasting**
* Broadcasting allows binary operation to be perfomed on array size of different size i-e we can perform binary operation on two different size array.

In [74]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print('a=>\n',a)

b=np.array([[1,2,3,4]])
print('b=>\n',b)

print(a+b)

a=>
 [[1 2 3 4]
 [5 6 7 8]]
b=>
 [[1 2 3 4]]
[[ 2  4  6  8]
 [ 6  8 10 12]]
